config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :permiso_perfils
  resources :perfils
  resources :permisos
  resources :donacions
  resources :actividads

  devise_for :users
  resources :users

  get '/actividades/pendientes', to: 'actividads#pendientes'
  get '/actividades/aprobadas', to: 'actividads#aprobadas'
  get 'aprobar_actividad', to: 'actividads#aprobar_actividad'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'actividads#index'
end

app/models/permiso_perfil.rb
class PermisoPerfil < ApplicationRecord
  belongs_to :perfil
  belongs_to :permiso
end

app/controllers/permiso_perfils_controller.rb
class PermisoPerfilsController < ApplicationController
  before_action :set_permiso_perfil, only: [:show, :edit, :update, :destroy]

  # GET /permiso_perfils
  # GET /permiso_perfils.json
  def index
    @permiso_perfils = PermisoPerfil.all
  end

  # GET /permiso_perfils/1
  # GET /permiso_perfils/1.json
  def show
  end

  # GET /permiso_perfils/new
  def new
    @permiso_perfil = PermisoPerfil.new
  end

  # GET /permiso_perfils/1/edit
  def edit
  end

  # POST /permiso_perfils
  # POST /permiso_perfils.json
  def create
    @permiso_perfil = PermisoPerfil.new(permiso_perfil_params)

    respond_to do |format|
      if @permiso_perfil.save
        format.html { redirect_to @permiso_perfil, notice: 'Permiso perfil was successfully created.' }
        format.json { render :show, status: :created, location: @permiso_perfil }
      else
        format.html { render :new }
        format.json { render json: @permiso_perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permiso_perfils/1
  # PATCH/PUT /permiso_perfils/1.json
  def update
    respond_to do |format|
      if @permiso_perfil.update(permiso_perfil_params)
        format.html { redirect_to @permiso_perfil, notice: 'Permiso perfil was successfully updated.' }
        format.json { render :show, status: :ok, location: @permiso_perfil }
      else
        format.html { render :edit }
        format.json { render json: @permiso_perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permiso_perfils/1
  # DELETE /permiso_perfils/1.json
  def destroy
    @permiso_perfil.destroy
    respond_to do |format|
      format.html { redirect_to permiso_perfils_url, notice: 'Permiso perfil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permiso_perfil
      @permiso_perfil = PermisoPerfil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permiso_perfil_params
      params.require(:permiso_perfil).permit(:perfil_id, :permiso_id, :concedido)
    end
end

app/helpers/permiso_perfils_helper.rb
module PermisoPerfilsHelper
end

app/views/permiso_perfils/_form.html.erb
<%= form_with(model: permiso_perfil, local: true) do |form| %>
  <% if permiso_perfil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permiso_perfil.errors.count, "error") %> prohibited this permiso_perfil from being saved:</h2>

      <ul>
      <% permiso_perfil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :perfil_id %>
    <%= form.text_field :perfil_id, id: :permiso_perfil_perfil_id %>
  </div>

  <div class="field">
    <%= form.label :permiso_id %>
    <%= form.text_field :permiso_id, id: :permiso_perfil_permiso_id %>
  </div>

  <div class="field">
    <%= form.label :concedido %>
    <%= form.check_box :concedido, id: :permiso_perfil_concedido %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/permiso_perfils/edit.html.erb
<h1>Editing Permiso Perfil</h1>

<%= render 'form', permiso_perfil: @permiso_perfil %>

<%= link_to 'Show', @permiso_perfil %> |
<%= link_to 'Back', permiso_perfils_path %>

app/views/permiso_perfils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permiso Perfils</h1>

<table>
  <thead>
    <tr>
      <th>Perfil</th>
      <th>Permiso</th>
      <th>Concedido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permiso_perfils.each do |permiso_perfil| %>
      <tr>
        <td><%= permiso_perfil.perfil %></td>
        <td><%= permiso_perfil.permiso %></td>
        <td><%= permiso_perfil.concedido %></td>
        <td><%= link_to 'Show', permiso_perfil %></td>
        <td><%= link_to 'Edit', edit_permiso_perfil_path(permiso_perfil) %></td>
        <td><%= link_to 'Destroy', permiso_perfil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permiso Perfil', new_permiso_perfil_path %>

app/views/permiso_perfils/new.html.erb
<h1>New Permiso Perfil</h1>

<%= render 'form', permiso_perfil: @permiso_perfil %>

<%= link_to 'Back', permiso_perfils_path %>

app/views/permiso_perfils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Perfil:</strong>
  <%= @permiso_perfil.perfil %>
</p>

<p>
  <strong>Permiso:</strong>
  <%= @permiso_perfil.permiso %>
</p>

<p>
  <strong>Concedido:</strong>
  <%= @permiso_perfil.concedido %>
</p>

<%= link_to 'Edit', edit_permiso_perfil_path(@permiso_perfil) %> |
<%= link_to 'Back', permiso_perfils_path %>