config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :permiso_perfils
  resources :perfils
  resources :permisos
  resources :donacions
  resources :actividads

  devise_for :users
  resources :users

  get '/actividades/pendientes', to: 'actividads#pendientes'
  get '/actividades/aprobadas', to: 'actividads#aprobadas'
  get 'aprobar_actividad', to: 'actividads#aprobar_actividad'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'actividads#index'
end

app/models/permiso.rb
class Permiso < ApplicationRecord
end

app/controllers/permisos_controller.rb
class PermisosController < ApplicationController
  before_action :set_permiso, only: [:show, :edit, :update, :destroy]

  # GET /permisos
  # GET /permisos.json
  def index
    @permisos = Permiso.all
  end

  # GET /permisos/1
  # GET /permisos/1.json
  def show
  end

  # GET /permisos/new
  def new
    @permiso = Permiso.new
  end

  # GET /permisos/1/edit
  def edit
  end

  # POST /permisos
  # POST /permisos.json
  def create
    @permiso = Permiso.new(permiso_params)

    respond_to do |format|
      if @permiso.save
        format.html { redirect_to @permiso, notice: 'Permiso was successfully created.' }
        format.json { render :show, status: :created, location: @permiso }
      else
        format.html { render :new }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permisos/1
  # PATCH/PUT /permisos/1.json
  def update
    respond_to do |format|
      if @permiso.update(permiso_params)
        format.html { redirect_to @permiso, notice: 'Permiso was successfully updated.' }
        format.json { render :show, status: :ok, location: @permiso }
      else
        format.html { render :edit }
        format.json { render json: @permiso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permisos/1
  # DELETE /permisos/1.json
  def destroy
    @permiso.destroy
    respond_to do |format|
      format.html { redirect_to permisos_url, notice: 'Permiso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permiso
      @permiso = Permiso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permiso_params
      params.require(:permiso).permit(:nombre)
    end
end

app/helpers/permisos_helper.rb
module PermisosHelper
end

app/views/permisos/_form.html.erb
<%= form_with(model: permiso, local: true) do |form| %>
  <% if permiso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permiso.errors.count, "error") %> prohibited this permiso from being saved:</h2>

      <ul>
      <% permiso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :permiso_nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/permisos/edit.html.erb
<h1>Editing Permiso</h1>

<%= render 'form', permiso: @permiso %>

<%= link_to 'Show', @permiso %> |
<%= link_to 'Back', permisos_path %>

app/views/permisos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permisos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permisos.each do |permiso| %>
      <tr>
        <td><%= permiso.nombre %></td>
        <td><%= link_to 'Show', permiso %></td>
        <td><%= link_to 'Edit', edit_permiso_path(permiso) %></td>
        <td><%= link_to 'Destroy', permiso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permiso', new_permiso_path %>

app/views/permisos/new.html.erb
<h1>New Permiso</h1>

<%= render 'form', permiso: @permiso %>

<%= link_to 'Back', permisos_path %>

app/views/permisos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @permiso.nombre %>
</p>

<%= link_to 'Edit', edit_permiso_path(@permiso) %> |
<%= link_to 'Back', permisos_path %>