config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :permiso_perfils
  resources :perfils
  resources :permisos
  resources :donacions
  resources :actividads

  devise_for :users
  resources :users

  get '/actividades/pendientes', to: 'actividads#pendientes'
  get '/actividades/aprobadas', to: 'actividads#aprobadas'
  get 'aprobar_actividad', to: 'actividads#aprobar_actividad'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'actividads#index'
end

app/models/perfil.rb
class Perfil < ApplicationRecord
end

app/controllers/perfils_controller.rb
class PerfilsController < ApplicationController
  before_action :set_perfil, only: [:show, :edit, :update, :destroy]

  # GET /perfils
  # GET /perfils.json
  def index
    @perfils = Perfil.all
  end

  # GET /perfils/1
  # GET /perfils/1.json
  def show
  end

  # GET /perfils/new
  def new
    @perfil = Perfil.new
  end

  # GET /perfils/1/edit
  def edit
  end

  # POST /perfils
  # POST /perfils.json
  def create
    @perfil = Perfil.new(perfil_params)

    respond_to do |format|
      if @perfil.save
        format.html { redirect_to @perfil, notice: 'Perfil creado exitosamente.' }
        format.json { render :show, status: :created, location: @perfil }
      else
        format.html { render :new }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfils/1
  # PATCH/PUT /perfils/1.json
  def update
    respond_to do |format|
      if @perfil.update(perfil_params)
        format.html { redirect_to @perfil, notice: 'Perfil actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @perfil }
      else
        format.html { render :edit }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfils/1
  # DELETE /perfils/1.json
  def destroy
    @perfil.destroy
    respond_to do |format|
      format.html { redirect_to perfils_url, notice: 'Perfil eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfil
      @perfil = Perfil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfil_params
      params.require(:perfil).permit(:nombre)
    end
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/views/perfils/_form.html.erb
<div class="container new_container">
  <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
      <% if perfil.id? %>
          <div class="panel-heading" style="color: white;background-color: #8e476c;border-color: #bce8f1;">
            <div class="panel-title">Editar Perfil</div>
          </div>
        <%else%>
          <div class="panel-heading" style="color: white;background-color: #8e476c;border-color: #bce8f1;">
            <div class="panel-title">Nuevo perfil</div>
          </div>
      <%end %>
      <div class="panel-body" style="color: white;background-color: #8e476c;border-color: #bce8f1;"> 
        <div  style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
        <%= form_with(model: perfil, local: true) do |form| %>
          <div class="form-group input-group">
              <div class="input-group-prepend" >
                <span class="input-group-text" style="padding-right: 10px;"> <i class="glyphicon glyphicon-user"></i> </span>
              </div>
              <%= form.text_field :nombre, id: :perfil_nombre, placeholder: 'Nombre',style:"color: black;" %>
          </div>
          <div class="actions">
              
              <%= form.submit %>
              
              <%= link_to 'Volver', perfils_path,class:"btn new_btn2",style:"height:35px;" %>
          </div>
        <% end %>      
      </div>
    </div>
  </div>
</div>

app/views/perfils/edit.html.erb
<%= render 'form', perfil: @perfil %>

app/views/perfils/index.html.erb
<div style="color: #ffc000; padding-right: 3%; padding-left: 3%;">



<div class="jumbotron" style="background: #9d5569;padding-right: 4%;padding-top: 2%;margin-top: 4%;">
  <div style="text-align: center;"><h2>Perfiles</h2></div>
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody  style="border: 0px solid #ffc000">
    <% @perfils.each do |perfil| %>
      <tr>
        <td><%= perfil.nombre %></td>
        <td><%= link_to raw("<i class='material-icons'>remove_red_eye</i>"), perfil,style:"color: #ffc000" %></td>
        <td><%= link_to raw("<i class='material-icons'>edit</i>"), edit_perfil_path(perfil),style:"color: #ffc000" %></td>
        <td><%= link_to raw("<i class='material-icons'>delete</i>"), perfil, method: :delete, data: { confirm: 'Are you sure?' },style:"color: #ffc000" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'Crear un perfil', new_perfil_path, class: "nav-link btn new_btn2",style:"width: 95%; margin-left:2%;" %>

</div>

app/views/perfils/new.html.erb
<%= render 'form', perfil: @perfil %>

app/views/perfils/show.html.erb
<div style="color: #ffc000;">
	<p>
	  <strong>Nombre:</strong>&nbsp;
	  <%= @perfil.nombre %>
	</p>

	<%= link_to raw("<i class='material-icons'>edit</i>"), edit_perfil_path(@perfil),style:"color:#ffc000;" %> |
	<%= link_to 'Volver', perfils_path,class:"btn  new_btn2" %>
</div>