config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :permiso_perfils
  resources :perfils
  resources :permisos
  resources :donacions
  resources :actividads

  devise_for :users
  resources :users

  get '/actividades/pendientes', to: 'actividads#pendientes'
  get '/actividades/aprobadas', to: 'actividads#aprobadas'
  get 'aprobar_actividad', to: 'actividads#aprobar_actividad'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'actividads#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaDisenio2</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.1/build/css/themes/bootstrap.min.css"/>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


    <% if notice != nil %>
      <script type="text/javascript">
        $(document).ready(function() {
            alertify.success("<%=notice%>");
        });
      </script>
    <%end%>

    <% if alert != nil %>
      <script type="text/javascript">
        $(document).ready(function() {
          alertify.error("<%=alert%>");
        });
      </script>
    <% end %>


  </head>
  <body>
<% if user_signed_in? %>
  <div id="header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light new_bg" style="margin-bottom: 0;">
    <%= link_to raw("<i class='material-icons' style='font-size: 44px; color: wheat;'>public</i>"), actividads_path, class: "navbar-brand",style:"height: 0%;" %> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse new_collapse "  id="navbarSupportedContent" style="height: 120px;">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? && current_user.perfil.nombre == "Administrador" %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #ffc000;">
                Usuarios
              </a>
              <div class="dropdown-menu new_ddl" aria-labelledby="navbarDropdown">
                <%= link_to 'Usuarios', users_path, class: 'dropdown-item',style:"color: #ffc107;"%>
              </div>
            </li>
          <%end%>
          <% if user_signed_in? && current_user.perfil.nombre == "Administrador" %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #ffc000;">
              Perfiles
            </a>
            <div class="dropdown-menu new_ddl" aria-labelledby="navbarDropdown">
              <%= link_to 'Ver Todos', perfils_path , class: 'dropdown-item',style:"color: #ffc107;"%>
              <div class="dropdown-divider" style="background-color: #ffc107; border:0.5px solid #ffc000 "></div>
              <%= link_to 'Crear Perfil', new_perfil_path , class: 'dropdown-item',style:"color: #ffc107;" %>
            </div>
          </li>
          <%end%>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #ffc000;">
              Actividades
            </a>
            <div class="dropdown-menu new_ddl" aria-labelledby="navbarDropdown">
              <% if  user_signed_in? && current_user.perfil.nombre == "Voluntario" || current_user.perfil.nombre == "Administrador"  %>
                <%= link_to 'Ver Todas', actividads_path , class: 'dropdown-item',style:"color: #ffc107;"%>
                <div class="dropdown-divider" style="background-color: #ffc107; border:0.5px solid #ffc000 "></div>
              <% end %>
              <% if user_signed_in? && current_user.perfil.nombre == "Voluntario" %>
                <%= link_to 'Ver mis actividades', '/actividades/pendientes' , class: 'dropdown-item',style:"color: #ffc107;"%>
                <div class="dropdown-divider" style="background-color: #ffc107; border:0.5px solid #ffc000 "></div>
              <%end%>
              <%= link_to 'Ver Aprobadas', '/actividades/aprobadas' , class: 'dropdown-item',style:"color: #ffc107;" %>
            </div>
          </li>
          <% if user_signed_in? && current_user.perfil.nombre == "Donante" %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #ffc000;">
                Donaciones
              </a>
              <div class="dropdown-menu new_ddl" aria-labelledby="navbarDropdown">
                <%= link_to 'Mis Donaciones', donacions_path , class: 'dropdown-item',style:"color: #ffc107;"%>
                <div class="dropdown-divider" style="background-color: #ffc107; border:0.5px solid #ffc000 "></div>
                <%= link_to 'Hacer Donacion', new_Donacion_path  , class: 'dropdown-item',style:"color: #ffc107;"%>
              </div>
            </li>
          <% end %>
          <% if user_signed_in? && current_user.perfil.nombre == "Administrador" %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #ffc000;">
                Gráficas
              </a>
              <div class="dropdown-menu new_ddl" aria-labelledby="navbarDropdown">
                <%= link_to 'Gráficas', home_index_path , class: 'dropdown-item',style:"color: #ffc107;"%>
              </div>
            </li>
          <% end %>
          
            <%= render "devise/shared/links" %>          
        </ul>
      </div>
    </nav>
  </div>
<% end %>
  
  	<p class="notice" style="display: none;"><%= notice %></p>
    <p class="alert"  style="display: none;"><%= alert %></p>
    <%= yield %>
    

  </body>

</html>